version: '3.8'

networks:
  oddny-network:
    driver: bridge

services:
  directus:
    build: ./directus
    ports:
      - '8055:8055'
    environment:
      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/database.sqlite
      PUBLIC_URL: 'https://oddny.appfront.nl/cms'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'https://oddny.appfront.nl,https://oddny.appfront.nl/cms,true'
    restart: unless-stopped
    networks:
      - oddny-network

  astro:
    build:
      context: ./astro
      args:
        - DIRECTUS_URL=http://directus:8055
    ports:
      - '4321:4321'
    depends_on:
      - directus
    environment:
      DIRECTUS_URL: 'http://directus:8055'
      PUBLIC_DIRECTUS_URL: 'https://oddny.appfront.nl/cms'
      HOST: '0.0.0.0'
      PORT: '4321'
    restart: unless-stopped
    networks:
      - oddny-network

  nginx:
    image: nginx:1.27-alpine
    ports:
      - '80:80'
      - '8083:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - directus
      - astro
    restart: unless-stopped
    networks:
      - oddny-network