version: '3.8'

services:
  directus:
    image: directus/directus:11
    ports:
      - '8055:8055'
    volumes:
      - ./directus/database.sqlite:/directus/database/database.sqlite
      - ./directus/uploads:/directus/uploads
    environment:
      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/database.sqlite
      PUBLIC_URL: 'https://oddny.appfront.nl/cms'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'https://oddny.appfront.nl,https://oddny.appfront.nl/cms,true'
    restart: unless-stopped

  astro:
    build: ./astro
    ports:
      - '4321:4321'
    depends_on:
      - directus
    environment:
      DIRECTUS_URL: 'http://directus:8055'
      PUBLIC_DIRECTUS_URL: 'https://oddny.appfront.nl/cms'
      HOST: '0.0.0.0'
      PORT: '4321'
    restart: unless-stopped